# Generated by Django 6.0.4 on 2026-04-23 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KS2Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor', models.CharField(default='', max_length=255, verbose_name='Инвестор')),
                ('okpo_investor', models.CharField(blank=True, max_length=20, verbose_name='ОКПО инвестора')),
                ('customer', models.CharField(default='АО «МОЭнергоСервис»', max_length=255, verbose_name='Заказчик')),
                ('okpo_customer', models.CharField(blank=True, max_length=20, verbose_name='ОКПО заказчика')),
                ('contractor', models.CharField(default='', max_length=255, verbose_name='Подрядчик')),
                ('okpo_contractor', models.CharField(blank=True, max_length=20, verbose_name='ОКПО подрядчика')),
                ('construction', models.CharField(default='', max_length=255, verbose_name='Наименование строительства')),
                ('object_name', models.CharField(default='', max_length=255, verbose_name='Объект')),
                ('okdp', models.CharField(blank=True, max_length=20, verbose_name='ОКДП')),
                ('document_number', models.CharField(default='', max_length=50, verbose_name='Номер документа')),
                ('contract_number', models.CharField(default='N4', max_length=50, verbose_name='Номер договора')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Дата договора')),
                ('day_contract', models.CharField(default='04', max_length=2, verbose_name='День заключения договора')),
                ('month_contract', models.CharField(default='09', max_length=2, verbose_name='Месяц заключения договора')),
                ('year_contract', models.CharField(default='2024', max_length=4, verbose_name='Год заключения договора')),
                ('report_from', models.DateField(blank=True, null=True, verbose_name='Отчет с')),
                ('report_to', models.DateField(blank=True, null=True, verbose_name='Отчет по')),
                ('smeta', models.CharField(default='', max_length=100, verbose_name='Стоимость по смете')),
                ('surrender_position', models.CharField(default='', max_length=255, verbose_name='Должность сдающего')),
                ('surrender_signature', models.CharField(default='', max_length=255, verbose_name='ФИО сдающего')),
                ('accept_position', models.CharField(default='', max_length=255, verbose_name='Должность принимающего')),
                ('accept_signature', models.CharField(default='', max_length=255, verbose_name='ФИО принимающего')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Форма КС-2',
                'verbose_name_plural': 'Формы КС-2',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KS3Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('ks2_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ks3_data', to='ks2.ks2form', verbose_name='Связанная форма КС-2')),
            ],
            options={
                'verbose_name': 'Форма КС-3',
                'verbose_name_plural': 'Формы КС-3',
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='', max_length=50, verbose_name='№ позиции')),
                ('name', models.CharField(default='', max_length=500, verbose_name='Наименование работы')),
                ('number_pricelist', models.CharField(default='-', max_length=50, verbose_name='№ прейскуранта')),
                ('unit_of_measurement', models.CharField(default='', max_length=50, verbose_name='Ед. измерения')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена за ед.')),
                ('ks2_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='ks2.ks2form', verbose_name='Форма КС-2')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'ordering': ['id'],
            },
        ),
    ]
